### ISSUE TITLE
Error: Unable to determine the domain name

### ISSUE THREAD

**Issue by veggiemonk** [lirantal/dockly#4]
Hi, 

I have this problem (with a nice error message by the way, so kudos for that).

How can I solve this?

Thanks in advance

```
Error: Unable to determine the domain name
    at new ClientRequest (_http_client.js:25:13)
    at Object.exports.request (http.js:31:10)
    at Object.request (/usr/local/lib/node_modules/dockly/node_modules/docker-modem/lib/http.js:51:52)
    at Object.get (/usr/local/lib/node_modules/dockly/node_modules/docker-modem/lib/http.js:80:19)
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/dockly/node_modules/docker-modem/lib/http.js:69:40)
    at ClientRequest.g (events.js:291:16)
    at emitOne (events.js:101:20)
    at ClientRequest.emit (events.js:188:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:474:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
```

**Comment by lirantal** [comment]
Hi @veggiemonk,

I released a couple of fixes for that last night already, can you please make sure you update dockly to the latest version from npm? 

The error message is actually originating from the native node.js http library which dockerode uses, yet it doesn't try/catch the error and so there's no way to handle it.
It will happen in cases where there is no way to connect to the docker daemon API or when it isn't able to detect any containers at all.

That should anyway be fixed now as I found other workarounds for it. Please update dockly and check again? Thanks!

**Comment by veggiemonk** [comment]
Updated to 1.1.2. It works !!! Thanks.

Just FYI, this is what happened when I tried to get the version from the command line:

```
dockly 1.1.2 by [object Object]
Interactive shell for managing Docker containers

/usr/local/lib/node_modules/dockly/node_modules/command-line-args/lib/argv.js:91
  throw err
  ^

UNKNOWN_OPTION: Unknown option: -v
    at halt (/usr/local/lib/node_modules/dockly/node_modules/command-line-args/lib/argv.js:89:15)
    at Argv.validate (/usr/local/lib/node_modules/dockly/node_modules/command-line-args/lib/argv.js:80:7)
    at commandLineArgs (/usr/local/lib/node_modules/dockly/node_modules/command-line-args/lib/command-line-args.js:42:8)
    at cliInit (/usr/local/lib/node_modules/dockly/src/cli.js:21:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/dockly/index.js:18:29)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

**Comment by lirantal** [comment]
I didn't add a version because just running dockly gives you that output, but I'll add it anyway :-)
Thanks!

**Comment by veggiemonk** [comment]
Don't worry, it is a habit to check the version before posting an issue....
Not really a feature request but it is easier for people to submit bug report.
Anyway, great work!!

**Comment by lirantal** [comment]
Thanks @veggiemonk!

I've also updated the cli usage now in case of issues:
![image](https://cloud.githubusercontent.com/assets/316371/20827536/6e0e4de2-b87b-11e6-82ba-09cc3e5af96a.png)

Pushed as another minor release to npm

**Comment by babarali581** [comment]
I have same Issue I am caking api  http.GET

**Comment by lirantal** [comment]
Hey @babarali581, not sure what you mean by "caking api http.GET".

Can you share more information about the system your using it on?
- Which dockly version installed?
- Docker version:
- Is docker available on the local socket?
- Are you trying to connect via host/port?
- Which OS and version:
