### ISSUE TITLE
Unexpected crash

### ISSUE THREAD

**Issue by omerlh** [lirantal/dockly#49]
## Expected Behavior
App work properly

## Actual Behavior

Crash suddenly with the following error:

```

Trace: TypeError: Cannot read property 'ApiVersion' of null
    at /usr/local/lib/node_modules/dockly/src/dockerUtil.js:121:33
    at /usr/local/lib/node_modules/dockly/node_modules/dockerode/lib/docker.js:1224:7
    at /usr/local/lib/node_modules/dockly/node_modules/docker-modem/lib/modem.js:262:7
    at getCause (/usr/local/lib/node_modules/dockly/node_modules/docker-modem/lib/modem.js:284:7)
    at Modem.buildPayload (/usr/local/lib/node_modules/dockly/node_modules/docker-modem/lib/modem.js:253:5)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/dockly/node_modules/docker-modem/lib/modem.js:229:14)
    at IncomingMessage.emit (events.js:165:20)
    at endReadableNT (_stream_readable.js:1101:12)
    at process._tickCallback (internal/process/next_tick.js:152:19)
    at exitError (/usr/local/lib/node_modules/dockly/index.js:88:13)
    at process.on (/usr/local/lib/node_modules/dockly/index.js:37:7)
    at process.emit (events.js:165:20)
    at process._fatalException (bootstrap_node.js:431:26)


```

## Steps to Re-produce the Problem

  1. I just run dockly and played while working on the container

## Context

- Operating System: OSX
- Node.js version (run `node --version`): v9.5.0
- Package version: latest
- Docker version (run `docker --version`): Docker version 17.12.0-ce, build c97c6d6
- Is docker installed locally? yes
- Do you have containers created? yes
- Does this file exists `/var/run/docker.sock` ? no
- Output of `docker info`:
```
Containers: 3
 Running: 2
 Paused: 0
 Stopped: 1
Images: 26
Server Version: 17.12.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.60-linuxkit-aufs
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.952GiB
Name: linuxkit-025000000001
ID: JLDG:MULK:4AT5:GMXH:TPPM:GZ2Y:BA75:EAAC:NEHR:CEJR:D6VR:MY6F
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 45
 Goroutines: 79
 System Time: 2018-02-13T15:00:22.720277167Z
 EventsListeners: 3
HTTP Proxy: docker.for.mac.http.internal:3128
HTTPS Proxy: docker.for.mac.http.internal:3129
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 docker-cache:5000
 127.0.0.0/8
Registry Mirrors:
 http://docker-cache:5000/
Live Restore Enabled: false


```

**Comment by lirantal** [comment]
Thanks @omerlh, I committed a fix and a new version should be published after CI runs with the fix available
